quotes = ["why are you like this",
          "shud up",
          "ok boomer",
          "yep, its gamer tiem",
          "it be like that....",
          "no",
          "I TOLD YOU ABOUT STAIRS BRO",
          "imigrants??..",
          "shut your fuck up boomer",
          "bruh moment",
          "i love american rapper, singer, songwriter, record producer, entrepreneur, and fashion designer kanye west",
          "this is definitely a bruh moment",
          "feet",
          "broeh thats thats cringe broeh",
          "just let me die already please",
          "oh god oh fuck",
          ":/",
          "shuf up libertarf",
          "help where am i",
          "penis",
          "sex",
          "valeu",
          "EVERY POSTS I HAVE EVER MADE ON THIS WEBSITE IS SATIRE. I DO NOT CONDONE NOR SUPPORT ANY OF THE OPINIONS EXPRESSED ON THIS IMAGEBOARD.\nAny post associated with this IP is satire and should be treated as such. At no point has anyone associated with this IP ever condoned, encouraged, committed or abated acts of violence or threats of violence against any persons, regardless of racial, ethnic, religious or cultural background.\nIn case of an investigation by any federal entity or similar, I do not have any involvement with this group or with the people in it, I do not know how I am here, probably added by a third party, I do not support any actions by the member of this website."
          ]
