quotes = ["why are you like this",
          "shud up",
          "ok",
          "yep, its gamer tiem",
          "it be like that....",
          "no",
          "I TOLD YOU ABOUT STAIRS BRO",
          "bruh moment",
          "i love american rapper, singer, songwriter, record producer, entrepreneur, and fashion designer kanye west",
          "this is definitely a bruh moment",
          "feet",
          "bro thats kinda cringe",
          "oh god oh fuck",
          "177013",
          "simpler times",
          "good one bro, i shall laugh",
          "i dont hit juuls i hit my wife and kids",
          "nnnnnngghghhhg i am a thirsty little flower and you have to water me\nplease use your piss",
          "should i jack off",
          "i will literally kick you",
          "im about to eat some soap",
          ":/",
          "it do not matter",
          "liberal",
          "help where am i",
          "penis",
          "sex",
          "oh no",
          "oh yes",
          "im gonna break your kneecaps",
          "cry about that you fucking baby",
          "owned",
          "how",
          "what",
          "CEASE",
          "american",
          "this is fucking terrifying",
          "LETS FUCKING GOOOOOOOOOOOOOOOO",
          "hello its me, dj erectile dysfunction, making you go hard because i cant",
          ]

lfgVariants = ["lets fucking go",
               "let's fucking go",
               "lets fuckin go",
               "let's fuckin go",
               ]

reactEmojisBroHaus = ["gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold",
                      "gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold","gold",
                      "bosnia","bosnia","bosnia","bosnia","bosnia","bosnia",
                      "POG",
                      "usami",
                      "miu","miuu",
                      "men",
                      "somethingwrong",
                      "saddoge",
                      "pissed",
                      "furious",
                      "delicious",
                      "content",
                      "dogewithit"]