quotes = ["why are you like this",
          "shud up",
          "ok boomer",
          "yep, its gamer tiem",
          "it be like that....",
          "no",
          "I TOLD YOU ABOUT STAIRS BRO",
          "imigrants??..",
          "shut your fuck up boomer",
          "bruh moment",
          "i love american rapper, singer, songwriter, record producer, entrepreneur, and fashion designer kanye west",
          "this is definitely a bruh moment",
          "feet",
          "broeh thats thats cringe broeh",
          "just let me die already please",
          "karen you whorj, despite 13% of dog tianmen square feet r*tarf",
          "oh god oh fuck",
          ":/",
          "shuf up libertarf",
          "help where am i",
          "penis",
          "sex"
          ]